std = "lua52"
max_line_length = 140

globals = { 
    "rom", 
    "public", 
    "config", 
    "modutil", 
    "game", 
    "chalk", 
    "reload", 
    "_PLUGIN", 
    "AdamantModpackLib_Runtime",
    "ScreenData",
    "TestCoordinator",
    "TestGameDeps",
    "TestGameCache",
    "TestHashing",
    "TestHooks",
    "TestIntegrations",
    "TestLogging",
    "TestMainBoot",
    "TestModuleHost",
    "TestModuleHost_CreateModule",
    "TestModuleHost_DefinitionContract",
    "TestModuleHost_IsEnabled",
    "TestModuleHost_PrepareDefinition",
    "TestModuleState_DataDefaults",
    "TestModuleState_Session",
    "TestModuleState_Store",
    "TestMutation",
    "TestMutation_BackupSystem",
    "TestMutation_DefinitionLifecycle",
    "TestOverlays",
    "TestOverlays_Retained",
    "TestStandaloneHost",
    "TestStorageValidation",
    "TestValues",
    "TestWidgets",
    "TestWidgets_Nav"
    }
read_globals = { 
    "imgui", 
    "import_as_fallback", 
    "import",
    "HUDScreen",
    "ImGuiTreeNodeFlags",
    "ModifyTextBox",
    "SetAlpha",
    "CreateComponentFromData",
    "Destroy",
    "ShowingCombatUI",
    "ImGuiComboFlags",
    "ImGuiCol"
    }
exclude_files = { "src/vendor/**/*.lua", "src/**/*template*.lua" }
