-- =============================================================================
-- Run all Lib tests
-- =============================================================================
-- Usage: lua tests/all.lua (from the adamant-modpack-Lib directory)

require('tests/TestMainBoot')
require('tests/TestLogging')
require('tests/TestValues')
require('tests/TestGameDeps')
require('tests/TestStorageValidation')
require('tests/TestHashing')
require('tests/TestModuleState_DataDefaults')
require('tests/TestModuleState_Store')
require('tests/TestModuleState_Session')
require('tests/TestGameCache')
require('tests/TestCoordinator')
require('tests/TestIntegrations')
require('tests/TestHooks')
require('tests/TestOverlays')
require('tests/TestOverlays_Retained')
require('tests/TestMutation_BackupSystem')
require('tests/TestMutation_DefinitionLifecycle')
require('tests/TestMutation')
require('tests/TestModuleHost')
require('tests/TestModuleHost_DefinitionContract')
require('tests/TestModuleHost_CreateModule')
require('tests/TestModuleHost_PrepareDefinition')
require('tests/TestModuleHost_IsEnabled')
require('tests/TestStandaloneHost')
require('tests/TestWidgets')
require('tests/TestWidgets_Nav')

local lu = require('luaunit')
os.exit(lu.LuaUnit.run())
